services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: unless-stopped
